baseURL = "https://n.zcz321.com/"
languageCode = "en-us"
title = "Lan's ✒ Note"
theme = "ananke"
[params]
  background_color_class = "bg-blue"
  body_classes = "avenir bg-white"
  twitter = "https://twitter.com/garyzhang11"

